---
esphome:
  name: test
  platformio_options:
    extra_scripts:
      - post:../../../export_compdb.py

esp32:
  board: esp32-s3-devkitc-1

wifi:
  ssid: wifi_ssid
  password: wifi_password
  fast_connect: true

logger:

external_components:
  - source: components

uart:
  id: uart_id
  tx_pin: GPIO43
  rx_pin: GPIO44
  baud_rate: 9600
  parity: NONE
  stop_bits: 1
  data_bits: 8

seeed_mr24hpb1:
  id: mr24hpb1
  uart_id: uart_id
  update_interval: 60s

binary_sensor:
  - platform: seeed_mr24hpb1
    presence:
      name: "Radar Presence"
    motion:
      name: "Radar Motion"

sensor:
  - platform: seeed_mr24hpb1
    movement_pct:
      name: "Radar Movement Percentage"

text_sensor:
  - platform: seeed_mr24hpb1
    movement_class:
      name: "Radar Movement Class"
    device_id:
      name: "Radar Device ID"
      entity_category: "diagnostic"
    software_version:
      name: "Radar Software Version"
      entity_category: "diagnostic"
    hardware_version:
      name: "Radar Hardware Version"
      entity_category: "diagnostic"
